language: r
cache: packages
r:
  - devel
  - release
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr);codecov()'
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
